"""
Django settings for frugalEarth project.

Generated by 'django-admin startproject' using Django 4.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qo57a=7_7#da$w#-(ug$zfmcw@on(goer(jr@@s9cjaq)pltnw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
#<<<<<<< HEAD


#=======
#>>>>>>> 840bf37d3ca46419406fb7ae06d5a6d9ec637024
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'pages.apps.PagesConfig',


    'django.contrib.sites',
    #'django.contrib.sites.models.Site',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',




]

AUTH_USER_MODEL = 'pages.User'

ASGI_APPLICATION = 'frugalEarth.asgi.application'

CHANNEL_LAYERS = {
    'default':{
        'BACKEND':'channels.layers.InMemoryChannelLayer'
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',


    #'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = 'frugalEarth.urls'

TEMPLATES = [

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR/"templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',


                #'social_django.context_processors.backends',
                #'social_django.context_processors.login_redirect',
            ],
        },
    },
]

SITE_ID = 2
ACCOUNT_EMAIL_VERIFICATION = "none"
LOGIN_REDIRECT_URL = 'feeds'
#LOGIN_URL= '/feeds/'
#ACCOUNT_LOGOUT_ON_GET = True

AUTHENTICATION_BACKENDS = (



    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)








AUTHENTICATION_BACKENDS = (
    #'social_core.backends.facebook.FacebookOAuth2',
    #'social_core.backends.twitter.TwitterOAuth',
    #'social_core.backends.github.GithubOAuth2',

    'django.contrib.auth.backends.ModelBackend',
)

WSGI_APPLICATION = 'frugalEarth.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',


    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

#SOCIAL_AUTH_FACEBOOK_KEY = '419831626882025'
#SOCIAL_AUTH_FACEBOOK_SECRET = '2f1fd921dcac813b0f0e2087003af289'
#SOCIAL_AUTH_URL_NAMESPACE = 'social'

#LOGIN_URL = 'login'
#LOGOUT_URL = 'logout'
#LOGIN_REDIRECT_URL = 'feeds'

#STATIC_URL = '/static/images/'
#MEDIA_URL = '/static/images/'

#STATIC_URL = '/static/'
#MEDIA_URL = '/static/images/'

#STATICFILES_DIRS = [
#    BASE_DIR / 'static'
#]

#STATIC_ROOT = BASE_DIR / 'static'

#MEDIA_ROOT = BASE_DIR / 'static/images'

STATIC_URL = '/static/'
MEDIA_URL = '/images/'

#STATICFILES_DIRS = [
#    BASE_DIR / 'static'
#]

STATIC_ROOT = BASE_DIR / 'static'

MEDIA_ROOT = BASE_DIR / 'static/images'

LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGIN_REDIRECT_URL = 'home'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#TALKJS_APP_ID = os.environ.get('tfpR0cQN')
#TALKJS_API_SECRET = os.environ.get('sk_test_GsEij9PXy2DewA3xK3CHJo4SHv9oWlPu')
#TALKJS_API_BASE_URL = os.environ.get('https://api.talkjs.com/v1/')


#SOCIAL_AUTH_FACEBOOK_KEY = '671617861185128'
#SOCIAL_AUTH_FACEBOOK_SECRET = 'b6234e6a35b219bdbccfc4f70948c107'
