# Generated by Django 4.1.1 on 2022-10-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_category_message_posts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='size',
            field=models.CharField(max_length=200),
        ),
    ]
