# Generated by Django 4.1.1 on 2022-10-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_posts_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='quantity',
            field=models.SmallIntegerField(),
        ),
    ]
