# Generated by Django 4.1.1 on 2022-10-06 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_posts_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='quantity',
        ),
    ]
