# Generated by Django 4.1.1 on 2022-10-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_posts_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='size',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
