# Generated by Django 4.1.1 on 2022-10-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_size_posts_quantity_remove_posts_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='notes',
            field=models.TextField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
