# Generated by Django 4.1.1 on 2022-10-08 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_posts_title_alter_posts_notes_delete_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['created']},
        ),
    ]
