# Generated by Django 4.1.1 on 2022-10-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_message_room_rename_title_category_name_delete_posts_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='title',
            new_name='name',
        ),
    ]
