# Generated by Django 4.1.1 on 2022-10-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_room_options_room_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='post',
            new_name='room',
        ),
    ]
